// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqdlqogacwovunmvgvmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZGxxb2dhY3dvdnVubXZndm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDAyMDIsImV4cCI6MjA2MDk3NjIwMn0.fZIWLcnyr5PpWrMTF0oLfEst-lkATpA4iZ8PPUFcrWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);